<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFDs8P1q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFDs8P1q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFDs8P1q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFDs8P1q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFDs8P1q\App_KernelDevDebugContainer([
    'container.build_hash' => 'FDs8P1q',
    'container.build_id' => '5e22cf4b',
    'container.build_time' => 1683831438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFDs8P1q');
